/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package vaim.io.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import vaim.core.graph.Graph;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-09T15:18:20.913Z[GMT]")
@Api(value = "load_graph", description = "the load_graph API")
public interface LoadGraphApi extends GeneralApi{

	@CrossOrigin(origins = ORIGIN)	
    @ApiOperation(value = "Loads a graph and its relevant (simulation) data into memory", nickname = "loadGraph", notes = "Loads a graph and its relevant (simulation) data into memory", response = Graph.class, tags={ "Action", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Graph loaded", response = Graph.class),
        @ApiResponse(code = 404, message = "Graph not found") })
    @RequestMapping(value = "/load_graph",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Graph> loadGraph(@NotNull @ApiParam(value = "The graph id to load.", required = true) @Valid @RequestParam(value = "graph_id", required = true) Integer graphId
,@NotNull @ApiParam(value = "Session variable to allow the server to recover information", required = true) @Valid @RequestParam(value = "session_id", required = true) String sessionId,
@NotNull @ApiParam(value = "The graph id to load.", required = true) @Valid @RequestParam(value = "res", required = false) Integer requestedResolution);

}

