/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package vaim.io.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import vaim.io.api.structures.GraphList;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-03-26T11:32:33.543Z[GMT]")
@Api(value = "load_available", description = "the load_available API")
public interface LoadAvailableApi extends GeneralApi{
	
	@CrossOrigin(origins = ORIGIN)
    @ApiOperation(value = "Lists all the graphs and simulations available", nickname = "loadAvailable", notes = "Lists all the graphs and simulations available", response = GraphList.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "listing succeeded", response = GraphList.class),
        @ApiResponse(code = 204, message = "no graphs to list"),
        @ApiResponse(code = 400, message = "error while processing request") })
    @RequestMapping(value = "/load_available",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GraphList> loadAvailable();

}
