/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package vaim.io.api;

import io.swagger.annotations.*;
import vaim.io.api.structures.Filelist;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-03-26T11:32:33.543Z[GMT]")
@Api(value = "show_local", description = "the show_local API")
public interface ShowLocalApi {

    @ApiOperation(value = "Loads the files for upload in the folder.", nickname = "showLocal", notes = "Shows the file list in the local folder to show the graphs to import", response = Filelist.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Filelist.class),
        @ApiResponse(code = 204, message = "No Elements"),
        @ApiResponse(code = 400, message = "Generic Error") })
    @RequestMapping(value = "/show_local",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Filelist> showLocal();

}
