/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package vaim.io.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import vaim.io.api.structures.ResolutionUpdate;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-09T15:18:20.913Z[GMT]")
@Api(value = "update_drawing_resolution", description = "the update_drawing_resolution API")
public interface UpdateDrawingResolutionApi extends GeneralApi{

	@CrossOrigin(origins = ORIGIN)	
    @ApiOperation(value = "Updates the matrices current resolution", nickname = "updateResolution", notes = "Updates the matrices current resolution", response = ResolutionUpdate.class, tags={ "Action", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sectors drawn", response = ResolutionUpdate.class),
        @ApiResponse(code = 404, message = "Graph not found") })
    @RequestMapping(value = "/update_drawing_resolution",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ResolutionUpdate> updateResolution(@NotNull @ApiParam(value = "The session id", required = true) @Valid @RequestParam(value = "session_id", required = true) String sessionId
,@NotNull @ApiParam(value = "the new resolution", required = true) @Valid @RequestParam(value = "newresolution", required = true) Integer newResolution
);

}

